#! /bin/sh

usage() {
cat <<EOF
usage: apple-doh [name] [url]
EOF
}
generate_doh() {
name=$1
url=$2
cat << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>Name</key>
			<string>$name DNS over HTTPS</string>
			<key>PayloadDescription</key>
			<string>Configures device to use $name DNS over HTTPS.</string>
			<key>PayloadDisplayName</key>
			<string>$name DoH</string>
			<key>PayloadIdentifier</key>
			<string>com.apple.dnsSettings.managed.$(cat /proc/sys/kernel/random/uuid)</string>
			<key>PayloadType</key>
			<string>com.apple.dnsSettings.managed</string>
			<key>PayloadUUID</key>
			<string>$(cat /proc/sys/kernel/random/uuid)</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
			<key>DNSSettings</key>
			<dict>
				<key>DNSProtocol</key>
				<string>HTTPS</string>
				<key>ServerURL</key>
				<string>$url</string>
			</dict>
		</dict>
	</array>
	<key>PayloadDescription</key>
	<string>Adds $name DoH to Big Sur and iOS 14 or newer systems</string>
	<key>PayloadDisplayName</key>
	<string>$name DoH</string>
	<key>PayloadIdentifier</key>
	<string>$(cat /proc/sys/kernel/random/uuid)</string>
	<key>PayloadRemovalDisallowed</key>
	<false/>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>$(cat /proc/sys/kernel/random/uuid)</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>
EOF
}

if [ $# -ne 2 ];then
	usage
	exit 1
fi
generate_doh $*
